services:
  # Migration Service - Runs before app and worker
  migration:
    image: ghcr.io/krish-kant/supercheck/migrate:latest
    environment:
      # Database Configuration
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/supercheck
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=supercheck
      
      # AWS S3 / MinIO Configuration
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - S3_ENDPOINT=http://minio:9000
      - S3_JOB_BUCKET_NAME=playwright-job-artifacts
      - S3_FORCE_PATH_STYLE=true
      - S3_OPERATION_TIMEOUT=10000
      - S3_MAX_RETRIES=3
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    networks:
      - supercheck-network

  # App (Next.js Frontend) - No longer handles migrations
  app:
    # image: supertest-app:latest
    image: ghcr.io/krish-kant/supercheck/app:latest
    ports:
      - "3000:3000"
    environment:
      # Database Configuration
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/supercheck
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=supercheck
      
      # Redis Configuration
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
      
      # App Configuration
      - NEXT_PUBLIC_APP_URL=http://127.0.0.1:3000
      - NODE_ENV=production
      - RUNNING_CAPACITY=5
      - QUEUED_CAPACITY=50
      - TEST_EXECUTION_TIMEOUT_MS=900000
      - TRACE_RECOVERY_INTERVAL_MS=300000
      
      # AWS S3 / MinIO Configuration
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - S3_ENDPOINT=http://minio:9000
      - S3_JOB_BUCKET_NAME=playwright-job-artifacts
      - S3_FORCE_PATH_STYLE=true
      - S3_OPERATION_TIMEOUT=10000
      - S3_MAX_RETRIES=3
      
      # Scheduler Configuration
      - DISABLE_JOB_SCHEDULER=false
      - DISABLE_MONITOR_SCHEDULER=false
    volumes:
      - ./app/public/tests:/app/public/tests
      - ./app/public/test-results:/app/public/test-results
      - ./app/public/artifacts:/app/public/artifacts
    depends_on:
      migration:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep next-server | grep -v grep"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - supercheck-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

  # Worker (NestJS Runner) - 2 replicas
  worker:
    # image: supertest-worker:latest
    image: ghcr.io/krish-kant/supercheck/worker:latest
    environment:
      # Database Configuration
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/supercheck
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=supercheck
      
      # Redis Configuration
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
      
      # App Configuration
      - NEXT_PUBLIC_APP_URL=http://127.0.0.1:3000
      - NODE_ENV=production
      - RUNNING_CAPACITY=5
      - QUEUED_CAPACITY=50
      - TEST_EXECUTION_TIMEOUT_MS=900000
      - TRACE_RECOVERY_INTERVAL_MS=300000
      
      # AWS S3 / MinIO Configuration
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - S3_ENDPOINT=http://minio:9000
      - S3_JOB_BUCKET_NAME=playwright-job-artifacts
      - S3_FORCE_PATH_STYLE=true
      - S3_OPERATION_TIMEOUT=10000
      - S3_MAX_RETRIES=3
      
      # Scheduler Configuration
      - DISABLE_JOB_SCHEDULER=false
      - DISABLE_MONITOR_SCHEDULER=false
    volumes:
      - ./runner/playwright-reports:/app/playwright-reports
      - ./runner/report:/app/report
    depends_on:
      migration:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "timeout", "5", "bash", "-c", "exec 3<>/dev/tcp/localhost/3001 && exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - supercheck-network
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

  # PostgreSQL Database
  postgres:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=supercheck
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - supercheck-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M

  # Redis (for job queues) - No persistence to avoid RDB format issues
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: sh -c "rm -rf /data/* && redis-server --maxmemory 256mb --maxmemory-policy noeviction --save '' --appendonly no"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - supercheck-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  # MinIO (S3-compatible storage)
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - supercheck-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  minio-data:
    driver: local

networks:
  supercheck-network:
    driver: bridge 