apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: supercheck-prod

resources:
  - ../../base

patchesStrategicMerge:
  - prod-patches.yaml

namePrefix: prod-

commonLabels:
  environment: production

replicas:
  - name: supercheck-app
    count: 2  # High availability
  - name: supercheck-worker
    count: 6  # More workers for production load