apiVersion: v1
kind: ConfigMap
metadata:
  name: supercheck-config
  namespace: supercheck
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_APP_URL: "https://supercheck.yourdomain.com"
  BETTER_AUTH_URL: "https://supercheck.yourdomain.com"
  RUNNING_CAPACITY: "12"  # Higher capacity for production
  QUEUED_CAPACITY: "100"
  PLAYWRIGHT_HEADLESS: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: supercheck
spec:
  template:
    spec:
      containers:
      - name: postgres
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: supercheck
spec:
  template:
    spec:
      containers:
      - name: redis
        command:
        - sh
        - -c
        - |
          rm -rf /data/* && \
          redis-server \
            --requirepass "${REDIS_PASSWORD}" \
            --maxmemory 512mb \
            --maxmemory-policy noeviction \
            --save '' \
            --appendonly no \
            --protected-mode yes \
            --bind 0.0.0.0
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: supercheck
spec:
  template:
    spec:
      containers:
      - name: minio
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supercheck-app
  namespace: supercheck
spec:
  template:
    spec:
      containers:
      - name: app
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "750m"
          limits:
            memory: "3Gi"
            cpu: "1500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supercheck-worker
  namespace: supercheck
spec:
  template:
    spec:
      containers:
      - name: worker
        resources:
          requests:
            memory: "1Gi"
            cpu: "750m"
          limits:
            memory: "2Gi"
            cpu: "1500m"