# Hetzner K3s Cluster Configuration for Supercheck Worker Service
# This configuration sets up a dedicated cluster for the worker service (test execution)
# Optimized for CPU-intensive workloads with Playwright test execution

# Replace with your actual Hetzner Cloud API token
hetzner_token: YOUR_HETZNER_API_TOKEN

# Cluster name
cluster_name: supercheck-worker

# Path where kubeconfig will be generated
kubeconfig_path: "./kubeconfig-worker"

# K3s version
k3s_version: v1.32.0+k3s1

# Networking configuration with security improvements
networking:
  ssh:
    port: 22
    use_agent: false
    public_key_path: "~/.ssh/id_ed25519.pub"
    private_key_path: "~/.ssh/id_ed25519"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api:
      - 10.1.0.0/16 # Different subnet to avoid conflicts with app cluster
  public_network:
    ipv4: true
    ipv6: true
  private_network:
    enabled: true # Enable private network for better security
    subnet: 10.1.0.0/16
  cni:
    enabled: true
    encryption: false # Not needed with private network
    mode: flannel # Simple and reliable for worker clusters

# Cluster CIDR settings (different from app cluster)
cluster_cidr: 10.245.0.0/16
service_cidr: 10.97.0.0/12
cluster_dns: 10.97.0.10

# Datastore configuration
datastore:
  mode: etcd # Use etcd for HA setup

# Master nodes configuration (HA setup)
masters_pool:
  instance_type: cpx21
  instance_count: 3
  locations:
    - fsn1 # Falkenstein
    - hel1 # Helsinki
    - nbg1 # Nuremberg

# Worker node pools optimized for test execution
worker_node_pools:
  - name: test-executors
    instance_type: cpx31 # More CPU for test execution
    instance_count: 3
    location: hel1
    autoscaling:
      enabled: true
      min_instances: 3
      max_instances: 10
  - name: heavy-executors
    instance_type: cpx41 # High CPU for intensive tests
    instance_count: 2
    location: fsn1
    autoscaling:
      enabled: true
      min_instances: 2
      max_instances: 8

# Embedded registry mirror for performance optimization
embedded_registry_mirror:
  enabled: true # Reduces external registry calls and improves pod startup times

# Protection settings
protect_against_deletion: true
create_load_balancer_for_the_kubernetes_api: true

# K3s upgrade concurrency
k3s_upgrade_concurrency: 1 # Conservative approach for stability

# Additional packages to install on all nodes
additional_packages:
  - ifupdown

# Additional commands to run after k3s installation
additional_post_k3s_commands:
  - apt update
  - apt upgrade -y
  - apt autoremove -y
  # Install additional dependencies for Playwright
  - apt-get install -y libnss3 libatk-bridge2.0-0 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libxss1 libasound2
