# Large Hetzner K3s Cluster Configuration for Supercheck
# This configuration follows Hetzner-k3s recommendations for clusters with 50+ nodes
# Includes custom firewall setup and IP query server configuration

# Replace with your actual Hetzner Cloud API token
hetzner_token: YOUR_HETZNER_API_TOKEN

# Cluster name
cluster_name: supercheck-k3s-large

# Path where kubeconfig will be generated
kubeconfig_path: "./kubeconfig"

# K3s version
k3s_version: v1.32.0+k3s1

# Networking configuration for large clusters
networking:
  ssh:
    port: 22
    use_agent: true # Recommended for large clusters
    public_key_path: "~/.ssh/id_ed25519.pub"
    private_key_path: "~/.ssh/id_ed25519"
  allowed_networks:
    ssh:
      - 0.0.0.0/0 # Required for public network access
    api:
      - 0.0.0.0/0 # Required when private network is disabled
  public_network:
    ipv4: true
    ipv6: true
    # Use custom IP query server for large clusters
    hetzner_ips_query_server_url: https://ip-query.example.com
    use_local_firewall: true # Enable custom firewall
  private_network:
    enabled: false # Disable private network for >100 nodes
  cni:
    enabled: true
    encryption: true # Enable encryption for public network
    mode: cilium # Better for large scale deployments

# Larger cluster CIDR ranges for more pods and services
cluster_cidr: 10.244.0.0/15 # Larger range for more pods
service_cidr: 10.96.0.0/16 # Larger range for more services
cluster_dns: 10.96.0.10

# Datastore configuration for large clusters
datastore:
  mode: etcd # Use etcd for HA setup
  # For very large clusters, consider external datastore:
  # external_datastore_endpoint: postgres://...

# Master nodes configuration for large clusters
masters_pool:
  instance_type: cpx31 # Larger instance type for masters
  instance_count: 3
  locations:
    - nbg1
    - hel1
    - fsn1

# Worker node pools for different workloads
worker_node_pools:
  - name: compute
    instance_type: cpx41
    location: nbg1
    autoscaling:
      enabled: true
      min_instances: 5
      max_instances: 50
  - name: storage
    instance_type: cpx51
    location: hel1
    autoscaling:
      enabled: true
      min_instances: 3
      max_instances: 20
  - name: app-workers
    instance_type: cpx31
    location: fsn1
    autoscaling:
      enabled: true
      min_instances: 3
      max_instances: 15

# Embedded registry mirror for performance optimization
embedded_registry_mirror:
  enabled: true # Recommended for large clusters

# Protection settings
protect_against_deletion: true
create_load_balancer_for_the_kubernetes_api: true

# K3s upgrade concurrency for large clusters
k3s_upgrade_concurrency: 2 # Can upgrade more nodes simultaneously

# Additional packages to install on all nodes
additional_packages:
  - ifupdown

# Additional commands to run after k3s installation
additional_post_k3s_commands:
  - apt update
  - apt upgrade -y
  - apt autoremove -y
