apiVersion: apps/v1
kind: Deployment
metadata:
  name: supercheck-app
  namespace: supercheck
  labels:
    app: supercheck-app
    component: frontend
spec:
  replicas: 2  # High availability for production
  selector:
    matchLabels:
      app: supercheck-app
  template:
    metadata:
      labels:
        app: supercheck-app
        component: frontend
    spec:
      # No init containers needed - external services are always available
      containers:
      - name: app
        image: ghcr.io/supercheck-io/supercheck/app:1.0.5-beta
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: supercheck-config
        - secretRef:
            name: supercheck-secrets
        env:
        # Additional environment variables for external services
        - name: DATABASE_POOL_MIN
          value: "2"
        - name: DATABASE_POOL_MAX
          value: "10"
        - name: REDIS_POOL_SIZE
          value: "5"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60  # Reduced since no DB migrations needed
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 3000
          initialDelaySeconds: 20  # Faster startup with external services
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 2
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        # Security context for production
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        # No volume mounts needed - using external S3
      # Anti-affinity for high availability
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - supercheck-app
              topologyKey: kubernetes.io/hostname