apiVersion: v1
kind: ConfigMap
metadata:
  name: supercheck-config
  namespace: supercheck
  labels:
    app.kubernetes.io/name: supercheck
    app.kubernetes.io/component: config
data:
  # App Configuration
  NEXT_PUBLIC_APP_URL: "https://supercheck.yourdomain.com"
  BETTER_AUTH_URL: "https://supercheck.yourdomain.com"
  NODE_ENV: "production"
  RUNNING_CAPACITY: "6"
  QUEUED_CAPACITY: "50"
  TEST_EXECUTION_TIMEOUT_MS: "120000"
  JOB_EXECUTION_TIMEOUT_MS: "900000"

  # External Database Configuration (Neon/PlanetScale)
  # Note: Full DATABASE_URL is set in secrets
  DB_SSL_MODE: "require"
  DB_CONNECTION_LIMIT: "10"
  DB_POOL_TIMEOUT: "30000"

  # External Redis Configuration (Redis Cloud)
  # Note: Full REDIS_URL is set in secrets
  REDIS_CONNECTION_TIMEOUT: "5000"
  REDIS_COMMAND_TIMEOUT: "5000"
  REDIS_MAX_RETRIES: "3"

  # External S3 Configuration (AWS S3 or compatible)
  AWS_REGION: "us-east-1"
  S3_JOB_BUCKET_NAME: "supercheck-job-artifacts"
  S3_TEST_BUCKET_NAME: "supercheck-test-artifacts"
  S3_FORCE_PATH_STYLE: "false"  # Set to true for MinIO compatibility
  S3_OPERATION_TIMEOUT: "10000"
  S3_MAX_RETRIES: "3"

  # Notification Channel Limits
  NEXT_PUBLIC_MAX_JOB_NOTIFICATION_CHANNELS: "10"
  NEXT_PUBLIC_MAX_MONITOR_NOTIFICATION_CHANNELS: "10"

  # Playwright Configuration
  PLAYWRIGHT_HEADLESS: "true"
  PLAYWRIGHT_RETRIES: "1"
  PLAYWRIGHT_TRACE: "on"
  PLAYWRIGHT_SCREENSHOT: "on"
  PLAYWRIGHT_VIDEO: "on"

  # Browser support
  ENABLE_FIREFOX: "false"
  ENABLE_WEBKIT: "false"
  ENABLE_MOBILE: "false"

  # Playground Cleanup Configuration
  PLAYGROUND_CLEANUP_ENABLED: "true"
  PLAYGROUND_CLEANUP_CRON: "0 */12 * * *"
  PLAYGROUND_CLEANUP_MAX_AGE_HOURS: "24"

  # Better Auth Admin Configuration
  SUPER_ADMIN_EMAILS: "admin@yourdomain.com"
  MAX_PROJECTS_PER_ORG: "10"
  DEFAULT_PROJECT_NAME: "Default Project"

  # SMTP Configuration
  SMTP_HOST: "smtp.resend.com"
  SMTP_PORT: "587"
  SMTP_USER: "resend"
  SMTP_SECURE: "false"
  SMTP_FROM_EMAIL: "notifications@yourdomain.com"

  # AI Fix Feature Configuration
  AI_PROVIDER: "openai"
  AI_MODEL: "gpt-4o-mini"
  AI_TIMEOUT_MS: "90000"
  AI_MAX_RETRIES: "2"
  AI_TEMPERATURE: "0.1"