# Dynamic configuration for Traefik
http:
  middlewares:
    # Rate limiting for API endpoints
    api-rate-limit:
      rateLimit:
        average: 50
        burst: 100
    
    # CORS middleware
    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowHeaders:
          - Content-Type
          - Authorization
          - X-Requested-With
        accessControlAllowOriginList:
          - "*"
        accessControlMaxAge: 86400
        addVaryHeader: true
    
    # Security headers
    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
    
    # Compression
    compress:
      compress: {}
    
    # API authentication (optional)
    api-auth:
      basicAuth:
        users:
          - "admin:$2y$10$8K1p/a0dL1LXMIgoEDFrwOfgqwAG6qYxR9V6JYfYHjqHjqHjqHjqH"  # admin:admin

  # Global rate limiting
  rateLimit:
    average: 100
    burst: 200 