# ConfigMap for environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: supercheck-config
  namespace: supercheck
data:
  # Database configuration (external)
  DATABASE_URL: "postgresql://user:password@your-external-db-host:5432/supercheck"
  DB_HOST: "your-external-db-host"
  DB_PORT: "5432"
  DB_USER: "your-db-user"
  DB_NAME: "supercheck"

  # Redis configuration (external)
  REDIS_HOST: "your-external-redis-host"
  REDIS_PORT: "6379"
  REDIS_URL: "redis://:password@your-external-redis-host:6379"

  # App configuration
  NEXT_PUBLIC_APP_URL: "https://supercheck.yourdomain.com"
  BETTER_AUTH_URL: "https://supercheck.yourdomain.com"
  BETTER_AUTH_SECRET: "your-super-secret-auth-key-change-this-in-production"
  NODE_ENV: "production"

  # Worker configuration
  RUNNING_CAPACITY: "5"
  QUEUED_CAPACITY: "100"
  MAX_CONCURRENT_EXECUTIONS: "2"
  TEST_EXECUTION_TIMEOUT_MS: "300000"
  JOB_EXECUTION_TIMEOUT_MS: "900000"

  # AWS S3 / MinIO Configuration
  AWS_REGION: "us-east-1"
  S3_ENDPOINT: "your-external-s3-host"
  S3_JOB_BUCKET_NAME: "playwright-job-artifacts"
  S3_TEST_BUCKET_NAME: "playwright-test-artifacts"
  S3_MONITOR_BUCKET_NAME: "playwright-monitor-artifacts"
  S3_FORCE_PATH_STYLE: "true"
  S3_OPERATION_TIMEOUT: "10000"
  S3_MAX_RETRIES: "3"

  # Notification Channel Limits
  NEXT_PUBLIC_MAX_JOB_NOTIFICATION_CHANNELS: "10"
  NEXT_PUBLIC_MAX_MONITOR_NOTIFICATION_CHANNELS: "10"

  # Playwright Configuration
  PLAYWRIGHT_HEADLESS: "true"
  PLAYWRIGHT_RETRIES: "1"
  PLAYWRIGHT_TRACE: "retain-on-failure"
  PLAYWRIGHT_SCREENSHOT: "only-on-failure"
  PLAYWRIGHT_VIDEO: "retain-on-failure"

  # Browser support
  ENABLE_FIREFOX: "false"
  ENABLE_WEBKIT: "false"
  ENABLE_MOBILE: "false"

  # Monitor Results Cleanup
  MONITOR_CLEANUP_ENABLED: "true"
  MONITOR_CLEANUP_CRON: "0 2 * * *"
  MONITOR_RETENTION_DAYS: "30"
  MONITOR_CLEANUP_BATCH_SIZE: "1000"
  MONITOR_PRESERVE_STATUS_CHANGES: "true"
  MONITOR_CLEANUP_SAFETY_LIMIT: "1000000"

  # Job Runs Cleanup
  JOB_RUNS_CLEANUP_ENABLED: "false"
  JOB_RUNS_CLEANUP_CRON: "0 3 * * *"
  JOB_RUNS_RETENTION_DAYS: "90"
  JOB_RUNS_CLEANUP_BATCH_SIZE: "100"
  JOB_RUNS_CLEANUP_SAFETY_LIMIT: "10000"

  # Playground Artifacts Cleanup
  PLAYGROUND_CLEANUP_ENABLED: "true"
  PLAYGROUND_CLEANUP_CRON: "0 */12 * * *"
  PLAYGROUND_CLEANUP_MAX_AGE_HOURS: "24"

  # Better Auth Admin Configuration
  MAX_PROJECTS_PER_ORG: "10"
  DEFAULT_PROJECT_NAME: "Default Project"

  # SMTP Email Configuration
  SMTP_HOST: "smtp.resend.com"
  SMTP_PORT: "587"
  SMTP_USER: "resend"
  SMTP_SECURE: "false"
  SMTP_FROM_EMAIL: "notification@example.com"

  # AI Fix Feature Configuration
  AI_PROVIDER: "openai"
  AI_MODEL: "gpt-4o-mini"
  AI_TIMEOUT_MS: "90000"
  AI_MAX_RETRIES: "2"
  AI_TEMPERATURE: "0.1"
