# Secret for sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: supercheck-secrets
  namespace: supercheck
type: Opaque
data:
  # Base64 encoded values
  DB_PASSWORD: <base64-encoded-password>
  REDIS_PASSWORD: <base64-encoded-password>
  AWS_ACCESS_KEY_ID: <base64-encoded-access-key>
  AWS_SECRET_ACCESS_KEY: <base64-encoded-secret-key>
  BETTER_AUTH_SECRET: <base64-encoded-auth-secret>
  CREDENTIAL_ENCRYPTION_KEY: <base64-encoded-credential-encryption-key>
  VARIABLES_ENCRYPTION_KEY: <base64-encoded-64-character-encryption-key>
  SMTP_PASSWORD: <base64-encoded-smtp-password>
  OPENAI_API_KEY: <base64-encoded-openai-api-key>
