# Supercheck Worker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supercheck-worker
  namespace: supercheck
  labels:
    app: supercheck-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: supercheck-worker
  template:
    metadata:
      labels:
        app: supercheck-worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/supercheck-io/supercheck/worker:latest
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=1024 --expose-gc --experimental-worker"
            - name: UV_THREADPOOL_SIZE
              value: "4"
          envFrom:
            - configMapRef:
                name: supercheck-config
            - secretRef:
                name: supercheck-secrets
          volumeMounts:
            - name: playwright-reports-volume
              mountPath: /app/playwright-reports
            - name: reports-volume
              mountPath: /app/report
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: playwright-reports-volume
          emptyDir: {}
        - name: reports-volume
          emptyDir: {}
