apiVersion: apps/v1
kind: Deployment
metadata:
  name: supercheck-app
  namespace: supercheck
  labels:
    app: supercheck-app
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supercheck-app
  template:
    metadata:
      labels:
        app: supercheck-app
        component: frontend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:18
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres-service -p 5432 -U postgres; do
                echo "Waiting for postgres..."
                sleep 2
              done
      containers:
        - name: app
          image: ghcr.io/supercheck-io/supercheck/app:1.0.5-beta
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: supercheck-config
            - secretRef:
                name: supercheck-secrets
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - name: tests-volume
              mountPath: /app/public/tests
            - name: test-results-volume
              mountPath: /app/public/test-results
            - name: artifacts-volume
              mountPath: /app/public/artifacts
      volumes:
        - name: tests-volume
          emptyDir: {}
        - name: test-results-volume
          emptyDir: {}
        - name: artifacts-volume
          emptyDir: {}
