apiVersion: v1
kind: ConfigMap
metadata:
  name: supercheck-config
  namespace: supercheck
  labels:
    app.kubernetes.io/name: supercheck
    app.kubernetes.io/component: config
data:
  # Database Configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "supercheck"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/supercheck"

  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_URL: "redis://:supersecure-redis-password-change-this@redis-service:6379"

  # App Configuration
  NEXT_PUBLIC_APP_URL: "http://localhost:3000"
  BETTER_AUTH_URL: "http://localhost:3000"
  NODE_ENV: "production"
  RUNNING_CAPACITY: "6"
  QUEUED_CAPACITY: "50"
  TEST_EXECUTION_TIMEOUT_MS: "120000"
  JOB_EXECUTION_TIMEOUT_MS: "900000"

  # AWS S3 / MinIO Configuration
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: "minioadmin"
  S3_ENDPOINT: "http://minio-service:9000"
  S3_JOB_BUCKET_NAME: "playwright-job-artifacts"
  S3_TEST_BUCKET_NAME: "playwright-test-artifacts"
  S3_FORCE_PATH_STYLE: "true"
  S3_OPERATION_TIMEOUT: "10000"
  S3_MAX_RETRIES: "3"

  # Notification Channel Limits
  NEXT_PUBLIC_MAX_JOB_NOTIFICATION_CHANNELS: "10"
  NEXT_PUBLIC_MAX_MONITOR_NOTIFICATION_CHANNELS: "10"

  # Monitor Configuration
  RECENT_MONITOR_RESULTS_LIMIT: "10000"

  # Playwright Configuration
  PLAYWRIGHT_HEADLESS: "true"
  PLAYWRIGHT_RETRIES: "1"
  PLAYWRIGHT_TRACE: "on"
  PLAYWRIGHT_SCREENSHOT: "on"
  PLAYWRIGHT_VIDEO: "on"

  # Browser support
  ENABLE_FIREFOX: "false"
  ENABLE_WEBKIT: "false"
  ENABLE_MOBILE: "false"

  # Playground Cleanup Configuration
  PLAYGROUND_CLEANUP_ENABLED: "true"
  PLAYGROUND_CLEANUP_CRON: "0 */12 * * *"
  PLAYGROUND_CLEANUP_MAX_AGE_HOURS: "24"

  # Better Auth Admin Configuration
  SUPER_ADMIN_EMAILS: "super.admin@example.com"
  MAX_PROJECTS_PER_ORG: "10"
  DEFAULT_PROJECT_NAME: "Default Project"

  # SMTP Configuration
  SMTP_HOST: "smtp.resend.com"
  SMTP_PORT: "587"
  SMTP_USER: "resend"
  SMTP_SECURE: "false"
  SMTP_FROM_EMAIL: "notification@example.com"

  # AI Fix Feature Configuration
  AI_PROVIDER: "openai"
  AI_MODEL: "gpt-4o-mini"
  AI_TIMEOUT_MS: "90000"
  AI_MAX_RETRIES: "2"
  AI_TEMPERATURE: "0.1"