apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - worker-deployment.yaml
  - worker-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - postgres-pvc.yaml
  - minio-deployment.yaml
  - minio-service.yaml
  - minio-pvc.yaml
  - ingress.yaml
  - config-map.yaml
  - secrets.yaml 