apiVersion: batch/v1
kind: Job
metadata:
  name: minio-bucket-init
  namespace: supercheck
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: mc
        image: minio/mc:latest
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: JOB_BUCKET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: S3_JOB_BUCKET_NAME
        - name: TEST_BUCKET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: S3_TEST_BUCKET_NAME
        command:
        - /bin/sh
        - -c
        - |
          mc alias set myminio http://minio:9000 "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" &&
          mc mb --ignore-existing myminio/$JOB_BUCKET &&
          mc mb --ignore-existing myminio/$TEST_BUCKET &&
          mc policy set download myminio/$JOB_BUCKET &&
          mc policy set download myminio/$TEST_BUCKET
      restartPolicy: OnFailure 