apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: supercheck
  labels:
    app: redis
    component: cache
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        component: cache
    spec:
      containers:
      - name: redis
        image: redis:8
        ports:
        - containerPort: 6379
          name: redis
        command:
        - sh
        - -c
        - |
          rm -rf /data/* && \
          redis-server \
            --requirepass "${REDIS_PASSWORD}" \
            --maxmemory 256mb \
            --maxmemory-policy noeviction \
            --save '' \
            --appendonly no \
            --protected-mode yes \
            --bind 0.0.0.0
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supercheck-secrets
              key: REDIS_PASSWORD
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - $(REDIS_PASSWORD)
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - $(REDIS_PASSWORD)
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc