apiVersion: apps/v1
kind: Deployment
metadata:
  name: supercheck-worker
  namespace: supercheck
  labels:
    app: supercheck-worker
    component: worker
spec:
  replicas: 4  # Matches docker-compose configuration
  selector:
    matchLabels:
      app: supercheck-worker
  template:
    metadata:
      labels:
        app: supercheck-worker
        component: worker
    spec:
      initContainers:
      - name: wait-for-app
        image: curlimages/curl:latest
        command:
        - sh
        - -c
        - |
          until curl -f http://supercheck-app-service:3000/; do
            echo "Waiting for app service to be ready..."
            sleep 5
          done
      containers:
      - name: worker
        image: ghcr.io/supercheck-io/supercheck/worker:1.0.5-beta
        ports:
        - containerPort: 3001
          name: http
        envFrom:
        - configMapRef:
            name: supercheck-config
        - secretRef:
            name: supercheck-secrets
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=1024 --expose-gc --experimental-worker"
        - name: UV_THREADPOOL_SIZE
          value: "4"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1.5Gi"
            cpu: "1500m"
            ephemeral-storage: "2Gi"  # For Playwright browser downloads
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: playwright-reports
          mountPath: /app/playwright-reports
        - name: reports
          mountPath: /app/report
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: playwright-reports
        emptyDir:
          sizeLimit: 1Gi
      - name: reports
        emptyDir:
          sizeLimit: 1Gi
      - name: tmp-volume
        emptyDir:
          sizeLimit: 512Mi