apiVersion: v1
kind: ConfigMap
metadata:
  name: supercheck-config
  namespace: supercheck
data:
  NODE_ENV: "development"
  NEXT_PUBLIC_APP_URL: "http://localhost:3000"
  BETTER_AUTH_URL: "http://localhost:3000"
  PLAYWRIGHT_HEADLESS: "false"  # Show browser in dev
  RUNNING_CAPACITY: "3"  # Lower capacity for dev
  QUEUED_CAPACITY: "10"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supercheck-app
  namespace: supercheck
spec:
  selector:
    matchLabels:
      app: supercheck-app
  template:
    spec:
      containers:
      - name: app
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supercheck-worker
  namespace: supercheck
spec:
  selector:
    matchLabels:
      app: supercheck-worker
  template:
    spec:
      containers:
      - name: worker
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"