name: Build Multi-Architecture Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push app image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/krish-kant/supercheck/app:latest

      - name: Build and push worker image
        uses: docker/build-push-action@v5
        with:
          context: ./runner
          file: ./runner/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/krish-kant/supercheck/worker:latest 